//! CColorScheme の既定色 / グラデーション / 枠線の定義テーブル(機械生成)。
//!
//! src/ColorScheme.cpp の m_ColorInfoList / m_GradientInfoList / m_BorderInfoList /
//! m_CustomDefaultBorderList から生成。色は HEXRGB(0xRRGGBB) を COLORREF へ変換。

use crate::indices::*;
use crate::{hexrgb, BorderInfo, ColorInfo, GradientInfo, CLR_INVALID};
use tvtest_theme::{BorderType, GradientDirection};

pub(crate) static COLOR_INFO_LIST: [ColorInfo; 234] = [
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "StatusBack", name: "ステータスバー 背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "StatusBack2", name: "ステータスバー 背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "StatusText", name: "ステータスバー 文字" },
    ColorInfo { default_color: hexrgb(0x777777), default_light_color: CLR_INVALID, text: "StatusItemBorder", name: "ステータスバー 項目外枠" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "StatusBottomItemBack", name: "ステータスバー 下段背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "StatusBottomItemBack2", name: "ステータスバー 下段背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "StatusBottomItemText", name: "ステータスバー 下段文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "StatusBottomItemBorder", name: "ステータスバー 下段外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "StatusHighlightBack", name: "ステータスバー 選択背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "StatusHighlightBack2", name: "ステータスバー 選択背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "StatusHighlightText", name: "ステータスバー 選択文字" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "StatusHighlightBorder", name: "ステータスバー 選択外枠" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "StatusBorder", name: "ステータスバー 外枠" },
    ColorInfo { default_color: hexrgb(0xDF3F00), default_light_color: CLR_INVALID, text: "StatusRecordingCircle", name: "ステータスバー 録画●" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "StatusEventProgressBack", name: "ステータスバー 番組経過時間背景1" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "StatusEventProgressBack2", name: "ステータスバー 番組経過時間背景2" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "StatusEventProgressBorder", name: "ステータスバー 番組経過時間外枠" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "StatusEventProgressElapsed", name: "ステータスバー 番組経過時間バー1" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "StatusEventProgressElapsed2", name: "ステータスバー 番組経過時間バー2" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "StatusEventProgressElapsedBorder", name: "ステータスバー 番組経過時間バー外枠" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "Splitter", name: "分割線" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ScreenBorder", name: "画面の外枠" },
    ColorInfo { default_color: hexrgb(0x555555), default_light_color: CLR_INVALID, text: "WindowFrame", name: "ウィンドウ 細枠" },
    ColorInfo { default_color: hexrgb(0x555555), default_light_color: CLR_INVALID, text: "WindowFrameBorder", name: "ウィンドウ 細枠の境界" },
    ColorInfo { default_color: hexrgb(0x666666), default_light_color: CLR_INVALID, text: "WindowActiveFrame", name: "ウィンドウ アクティブ細枠" },
    ColorInfo { default_color: hexrgb(0x666666), default_light_color: CLR_INVALID, text: "WindowActiveFrameBorder", name: "ウィンドウ アクティブ細枠の境界" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "PanelBack", name: "パネル 背景" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "PanelText", name: "パネル 文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "PanelTabBack", name: "パネル タブ背景1" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "PanelTabBack2", name: "パネル タブ背景2" },
    ColorInfo { default_color: hexrgb(0x888888), default_light_color: CLR_INVALID, text: "PanelTabText", name: "パネル タブ文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "PanelTabBorder", name: "パネル タブ外枠" },
    ColorInfo { default_color: hexrgb(0x555555), default_light_color: CLR_INVALID, text: "PanelCurTabBack", name: "パネル 選択タブ背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "PanelCurTabBack2", name: "パネル 選択タブ背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "PanelCurTabText", name: "パネル 選択タブ文字" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "PanelCurTabBorder", name: "パネル 選択タブ外枠" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "PanelTabMargin", name: "パネル タブ余白1" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "PanelTabMargin2", name: "パネル タブ余白2" },
    ColorInfo { default_color: hexrgb(0x888888), default_light_color: CLR_INVALID, text: "PanelTabMarginBorder", name: "パネル タブ余白外枠" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "PanelTabLine", name: "パネル タブ線" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "PanelTitleBack", name: "パネル タイトル背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "PanelTitleBack2", name: "パネル タイトル背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "PanelTitleText", name: "パネル タイトル文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "PanelTitleBorder", name: "パネル タイトル外枠" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "ProgramInfoBack", name: "情報パネル 番組情報背景" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ProgramInfoText", name: "情報パネル 番組情報文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "ProgramInfoBorder", name: "情報パネル 番組情報外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "InformationPanelButtonBack", name: "情報パネル ボタン背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "InformationPanelButtonBack2", name: "情報パネル ボタン背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "InformationPanelButtonText", name: "情報パネル ボタン文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "InformationPanelButtonBorder", name: "情報パネル ボタン境界" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "InformationPanelHotButtonBack", name: "情報パネル 選択ボタン背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "InformationPanelHotButtonBack2", name: "情報パネル 選択ボタン背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "InformationPanelHotButtonText", name: "情報パネル 選択ボタン文字" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "InformationPanelHotButtonBorder", name: "情報パネル 選択ボタン境界" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListChannelBack", name: "番組表パネル 局名背景1" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListChannelBack2", name: "番組表パネル 局名背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ProgramListChannelText", name: "番組表パネル 局名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListChannelBorder", name: "番組表パネル 局名外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ProgramListCurChannelBack", name: "番組表パネル 現在局名背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ProgramListCurChannelBack2", name: "番組表パネル 現在局名背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ProgramListCurChannelText", name: "番組表パネル 現在局名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListCurChannelBorder", name: "番組表パネル 現在局名外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonBack", name: "番組表パネル ボタン背景1" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonBack2", name: "番組表パネル ボタン背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonText", name: "番組表パネル ボタン文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonBorder", name: "番組表パネル ボタン外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonHotBack", name: "番組表パネル 選択ボタン背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonHotBack2", name: "番組表パネル 選択ボタン背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonHotText", name: "番組表パネル 選択ボタン文字" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ProgramListChannelButtonHotBorder", name: "番組表パネル 選択ボタン外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListBack", name: "番組表パネル 番組内容背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListBack2", name: "番組表パネル 番組内容背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "ProgramListText", name: "番組表パネル 番組内容文字" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ProgramListBorder", name: "番組表パネル 番組内容外枠" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "ProgramListCurBack", name: "番組表パネル 現在番組内容背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListCurBack2", name: "番組表パネル 現在番組内容背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ProgramListCurText", name: "番組表パネル 現在番組内容文字" },
    ColorInfo { default_color: hexrgb(0x555555), default_light_color: CLR_INVALID, text: "ProgramListCurBorder", name: "番組表パネル 現在番組内容外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramListTitleBack", name: "番組表パネル 番組名背景1" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListTitleBack2", name: "番組表パネル 番組名背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ProgramListTitleText", name: "番組表パネル 番組名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListTitleBorder", name: "番組表パネル 番組名外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ProgramListCurTitleBack", name: "番組表パネル 現在番組名背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ProgramListCurTitleBack2", name: "番組表パネル 現在番組名背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ProgramListCurTitleText", name: "番組表パネル 現在番組名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramListCurTitleBorder", name: "番組表パネル 現在番組名外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ChannelPanelChannelNameBack", name: "チャンネルパネル 局名背景1" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ChannelPanelChannelNameBack2", name: "チャンネルパネル 局名背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ChannelPanelChannelNameText", name: "チャンネルパネル 局名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ChannelPanelChannelNameBorder", name: "チャンネルパネル 局名外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ChannelPanelCurChannelNameBack", name: "チャンネルパネル 現在局名背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ChannelPanelCurChannelNameBack2", name: "チャンネルパネル 現在局名背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ChannelPanelCurChannelNameText", name: "チャンネルパネル 現在局名文字" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ChannelPanelCurChannelNameBorder", name: "チャンネルパネル 現在局名外枠" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ChannelPanelEventNameBack", name: "チャンネルパネル 番組名1背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ChannelPanelEventNameBack2", name: "チャンネルパネル 番組名1背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "ChannelPanelEventNameText", name: "チャンネルパネル 番組名1文字" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ChannelPanelEventNameBorder", name: "チャンネルパネル 番組名1外枠" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "ChannelPanelEventName2Back", name: "チャンネルパネル 番組名2背景1" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "ChannelPanelEventName2Back2", name: "チャンネルパネル 番組名2背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "ChannelPanelEventName2Text", name: "チャンネルパネル 番組名2文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ChannelPanelEventName2Border", name: "チャンネルパネル 番組名2外枠" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventNameBack", name: "チャンネルパネル 選択番組名1背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventNameBack2", name: "チャンネルパネル 選択番組名1背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventNameText", name: "チャンネルパネル 選択番組名1文字" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventNameBorder", name: "チャンネルパネル 選択番組名1外枠" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventName2Back", name: "チャンネルパネル 選択番組名2背景1" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventName2Back2", name: "チャンネルパネル 選択番組名2背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventName2Text", name: "チャンネルパネル 選択番組名2文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ChannelPanelCurEventName2Border", name: "チャンネルパネル 選択番組名2外枠" },
    ColorInfo { default_color: hexrgb(0x00FF00), default_light_color: CLR_INVALID, text: "ChannelPanelFeaturedMark", name: "チャンネルパネル 注目マーク背景1" },
    ColorInfo { default_color: hexrgb(0x00FF00), default_light_color: CLR_INVALID, text: "ChannelPanelFeaturedMark2", name: "チャンネルパネル 注目マーク背景2" },
    ColorInfo { default_color: hexrgb(0x00BF00), default_light_color: CLR_INVALID, text: "ChannelPanelFeaturedMarkBorder", name: "チャンネルパネル 注目マーク外枠" },
    ColorInfo { default_color: hexrgb(0x2D5899), default_light_color: CLR_INVALID, text: "ChannelPanelProgress", name: "チャンネルパネル 番組経過時間バー1" },
    ColorInfo { default_color: hexrgb(0x2D5899), default_light_color: CLR_INVALID, text: "ChannelPanelProgress2", name: "チャンネルパネル 番組経過時間バー2" },
    ColorInfo { default_color: hexrgb(0x2D5899), default_light_color: CLR_INVALID, text: "ChannelPanelProgressBorder", name: "チャンネルパネル 番組経過時間バー外枠" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "ChannelPanelCurProgress", name: "チャンネルパネル 選択番組経過時間バー1" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "ChannelPanelCurProgress2", name: "チャンネルパネル 選択番組経過時間バー2" },
    ColorInfo { default_color: hexrgb(0x3465B0), default_light_color: CLR_INVALID, text: "ChannelPanelCurProgressBorder", name: "チャンネルパネル 選択番組経過時間バー外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ControlPanelBack", name: "操作パネル 背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ControlPanelBack2", name: "操作パネル 背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "ControlPanelText", name: "操作パネル 文字" },
    ColorInfo { default_color: hexrgb(0x666666), default_light_color: CLR_INVALID, text: "ControlPanelItemBorder", name: "操作パネル 項目外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ControlPanelHighlightBack", name: "操作パネル 選択背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ControlPanelHighlightBack2", name: "操作パネル 選択背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ControlPanelHighlightText", name: "操作パネル 選択文字" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ControlPanelHighlightBorder", name: "操作パネル 選択項目外枠" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "ControlPanelCheckedBack", name: "操作パネル チェック背景1" },
    ColorInfo { default_color: hexrgb(0x555555), default_light_color: CLR_INVALID, text: "ControlPanelCheckedBack2", name: "操作パネル チェック背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ControlPanelCheckedText", name: "操作パネル チェック文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ControlPanelCheckedBorder", name: "操作パネル チェック項目外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ControlPanelMargin", name: "操作パネル 余白" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "CaptionPanelBack", name: "字幕パネル 背景" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "CaptionPanelText", name: "字幕パネル 文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "TitleBarBack", name: "タイトルバー 背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "TitleBarBack2", name: "タイトルバー 背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "TitleBarText", name: "タイトルバー 文字" },
    ColorInfo { default_color: hexrgb(0x777777), default_light_color: CLR_INVALID, text: "TitleBarTextBorder", name: "タイトルバー 文字外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "TitleBarIconBack", name: "タイトルバー アイコン背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "TitleBarIconBack2", name: "タイトルバー アイコン背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "TitleBarIcon", name: "タイトルバー アイコン" },
    ColorInfo { default_color: hexrgb(0x777777), default_light_color: CLR_INVALID, text: "TitleBarIconBorder", name: "タイトルバー アイコン外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "TitleBarHighlightBack", name: "タイトルバー 選択背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "TitleBarHighlightBack2", name: "タイトルバー 選択背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "TitleBarHighlightIcon", name: "タイトルバー 選択アイコン" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "TitleBarHighlightIconBorder", name: "タイトルバー 選択アイコン外枠" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "TitleBarBorder", name: "タイトルバー 外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "SideBarBack", name: "サイドバー 背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "SideBarBack2", name: "サイドバー 背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "SideBarIcon", name: "サイドバー アイコン" },
    ColorInfo { default_color: hexrgb(0x777777), default_light_color: CLR_INVALID, text: "SideBarItemBorder", name: "サイドバー 項目外枠" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "SideBarHighlightBack", name: "サイドバー 選択背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "SideBarHighlightBack2", name: "サイドバー 選択背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "SideBarHighlightIcon", name: "サイドバー 選択アイコン" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "SideBarHighlightBorder", name: "サイドバー 選択外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "SideBarCheckBack", name: "サイドバー チェック背景1" },
    ColorInfo { default_color: hexrgb(0x444444), default_light_color: CLR_INVALID, text: "SideBarCheckBack2", name: "サイドバー チェック背景2" },
    ColorInfo { default_color: hexrgb(0xAAAAAA), default_light_color: CLR_INVALID, text: "SideBarCheckIcon", name: "サイドバー チェックアイコン" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "SideBarCheckBorder", name: "サイドバー チェック外枠" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "SideBarBorder", name: "サイドバー 外枠" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: CLR_INVALID, text: "NotificationBarBack", name: "通知バー 背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "NotificationBarBack2", name: "通知バー 背景2" },
    ColorInfo { default_color: hexrgb(0xBBBBBB), default_light_color: CLR_INVALID, text: "NotificationBarText", name: "通知バー 文字" },
    ColorInfo { default_color: hexrgb(0xFF9F44), default_light_color: CLR_INVALID, text: "NotificationBarWarningText", name: "通知バー 警告文字" },
    ColorInfo { default_color: hexrgb(0xFF4444), default_light_color: CLR_INVALID, text: "NotificationBarErrorText", name: "通知バー エラー文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xFFFFFF), text: "EventInfoPopupBack", name: "番組情報ポップアップ 背景" },
    ColorInfo { default_color: hexrgb(0xBBBBBB), default_light_color: hexrgb(0x333333), text: "EventInfoPopupText", name: "番組情報ポップアップ 文字" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: hexrgb(0x000000), text: "EventInfoPopupEventTitle", name: "番組情報ポップアップ 番組名" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideBack", name: "EPG番組表 背景" },
    ColorInfo { default_color: hexrgb(0x222222), default_light_color: hexrgb(0x000000), text: "ProgramGuideText", name: "EPG番組表 番組内容" },
    ColorInfo { default_color: hexrgb(0x000000), default_light_color: CLR_INVALID, text: "ProgramGuideEventTitle", name: "EPG番組表 番組名" },
    ColorInfo { default_color: hexrgb(0x0000BF), default_light_color: CLR_INVALID, text: "ProgramGuideHighlightText", name: "EPG番組表 検索番組内容" },
    ColorInfo { default_color: hexrgb(0x0000FF), default_light_color: CLR_INVALID, text: "ProgramGuideHighlightTitle", name: "EPG番組表 検索番組名" },
    ColorInfo { default_color: hexrgb(0x9999FF), default_light_color: CLR_INVALID, text: "ProgramGuideHighlightBack", name: "EPG番組表 検索番組背景" },
    ColorInfo { default_color: hexrgb(0x6666FF), default_light_color: CLR_INVALID, text: "ProgramGuideHighlightBorder", name: "EPG番組表 検索番組枠" },
    ColorInfo { default_color: hexrgb(0xCCFFCC), default_light_color: CLR_INVALID, text: "ProgramGuideFeaturedMark", name: "EPG番組表 注目マーク背景1" },
    ColorInfo { default_color: hexrgb(0x99FF99), default_light_color: CLR_INVALID, text: "ProgramGuideFeaturedMark2", name: "EPG番組表 注目マーク背景2" },
    ColorInfo { default_color: hexrgb(0x00EF00), default_light_color: CLR_INVALID, text: "ProgramGuideFeaturedMarkBorder", name: "EPG番組表 注目マーク外枠" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: CLR_INVALID, text: "ProgramGuideChannelBack", name: "EPG番組表 チャンネル名背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: CLR_INVALID, text: "ProgramGuideChannelBack2", name: "EPG番組表 チャンネル名背景2" },
    ColorInfo { default_color: hexrgb(0x999999), default_light_color: CLR_INVALID, text: "ProgramGuideChannelText", name: "EPG番組表 チャンネル名文字" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ProgramGuideChannelHighlightText", name: "EPG番組表 チャンネル名強調文字" },
    ColorInfo { default_color: hexrgb(0x4486E8), default_light_color: CLR_INVALID, text: "ProgramGuideCurChannelBack", name: "EPG番組表 チャンネル名選択背景1" },
    ColorInfo { default_color: hexrgb(0x3C76CC), default_light_color: CLR_INVALID, text: "ProgramGuideCurChannelBack2", name: "EPG番組表 チャンネル名選択背景2" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: CLR_INVALID, text: "ProgramGuideCurChannelText", name: "EPG番組表 チャンネル名選択文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideTimeBack", name: "EPG番組表 日時背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideTimeBack2", name: "EPG番組表 日時背景2" },
    ColorInfo { default_color: hexrgb(0x00337F), default_light_color: hexrgb(0x004CBF), text: "ProgramGuideTime0To2Back", name: "EPG番組表 0～2時背景1" },
    ColorInfo { default_color: hexrgb(0x00193F), default_light_color: hexrgb(0x00337F), text: "ProgramGuideTime0To2Back2", name: "EPG番組表 0～2時背景2" },
    ColorInfo { default_color: hexrgb(0x00667F), default_light_color: hexrgb(0x0099BF), text: "ProgramGuideTime3To5Back", name: "EPG番組表 3～5時背景1" },
    ColorInfo { default_color: hexrgb(0x00333F), default_light_color: hexrgb(0x00667F), text: "ProgramGuideTime3To5Back2", name: "EPG番組表 3～5時背景2" },
    ColorInfo { default_color: hexrgb(0x007F66), default_light_color: hexrgb(0x00BF99), text: "ProgramGuideTime6To8Back", name: "EPG番組表 6～8時背景1" },
    ColorInfo { default_color: hexrgb(0x003F33), default_light_color: hexrgb(0x007F66), text: "ProgramGuideTime6To8Back2", name: "EPG番組表 6～8時背景2" },
    ColorInfo { default_color: hexrgb(0x667F00), default_light_color: hexrgb(0x99BF00), text: "ProgramGuideTime9To11Back", name: "EPG番組表 9～11時背景1" },
    ColorInfo { default_color: hexrgb(0x333F00), default_light_color: hexrgb(0x667F00), text: "ProgramGuideTime9To11Back2", name: "EPG番組表 9～11時背景2" },
    ColorInfo { default_color: hexrgb(0x7F6600), default_light_color: hexrgb(0xBF9900), text: "ProgramGuideTime12To14Back", name: "EPG番組表 12～14時背景1" },
    ColorInfo { default_color: hexrgb(0x3F3300), default_light_color: hexrgb(0x7F6600), text: "ProgramGuideTime12To14Back2", name: "EPG番組表 12～14時背景2" },
    ColorInfo { default_color: hexrgb(0x7F3300), default_light_color: hexrgb(0xBF4C00), text: "ProgramGuideTime15To17Back", name: "EPG番組表 15～17時背景1" },
    ColorInfo { default_color: hexrgb(0x3F1900), default_light_color: hexrgb(0x7F3300), text: "ProgramGuideTime15To17Back2", name: "EPG番組表 15～17間背景2" },
    ColorInfo { default_color: hexrgb(0x7F0066), default_light_color: hexrgb(0xBF0099), text: "ProgramGuideTime18To20Back", name: "EPG番組表 18～20時背景1" },
    ColorInfo { default_color: hexrgb(0x3F0033), default_light_color: hexrgb(0x7F0066), text: "ProgramGuideTime18To20Back2", name: "EPG番組表 18～20時背景2" },
    ColorInfo { default_color: hexrgb(0x66007F), default_light_color: hexrgb(0x9900BF), text: "ProgramGuideTime21To23Back", name: "EPG番組表 21～23時背景1" },
    ColorInfo { default_color: hexrgb(0x33003F), default_light_color: hexrgb(0x66007F), text: "ProgramGuideTime21To23Back2", name: "EPG番組表 21～23時背景2" },
    ColorInfo { default_color: hexrgb(0xBBBBBB), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideTimeText", name: "EPG番組表 時間文字" },
    ColorInfo { default_color: hexrgb(0x888888), default_light_color: CLR_INVALID, text: "ProgramGuideTimeLine", name: "EPG番組表 時間線" },
    ColorInfo { default_color: hexrgb(0xFF6600), default_light_color: CLR_INVALID, text: "ProgramGuideCurTimeLine", name: "EPG番組表 現在時刻線" },
    ColorInfo { default_color: hexrgb(0xBBBBBB), default_light_color: hexrgb(0x000000), text: "ProgramGuideDateButtonText", name: "EPG番組表 日付ボタン文字" },
    ColorInfo { default_color: hexrgb(0xFF3F1F), default_light_color: hexrgb(0xFF2000), text: "ProgramGuideDateButtonSundayText", name: "EPG番組表 日付ボタン日曜文字" },
    ColorInfo { default_color: hexrgb(0x4F9FFF), default_light_color: hexrgb(0x0020FF), text: "ProgramGuideDateButtonSaturdayText", name: "EPG番組表 日付ボタン土曜文字" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideDateButtonBack", name: "EPG番組表 日付ボタン背景1" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonBack2", name: "EPG番組表 日付ボタン背景2" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonBorder", name: "EPG番組表 日付ボタン外枠" },
    ColorInfo { default_color: hexrgb(0xDDDDDD), default_light_color: hexrgb(0x000000), text: "ProgramGuideDateButtonCurText", name: "EPG番組表 日付ボタン選択文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonCurBack", name: "EPG番組表 日付ボタン選択背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideDateButtonCurBack2", name: "EPG番組表 日付ボタン選択背景2" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonCurBorder", name: "EPG番組表 日付ボタン選択外枠" },
    ColorInfo { default_color: hexrgb(0xBBBBBB), default_light_color: hexrgb(0x000000), text: "ProgramGuideDateButtonHotText", name: "EPG番組表 日付ボタンホット文字" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonHotBack", name: "EPG番組表 日付ボタンホット背景1" },
    ColorInfo { default_color: hexrgb(0x333333), default_light_color: hexrgb(0xFFFFFF), text: "ProgramGuideDateButtonHotBack2", name: "EPG番組表 日付ボタンホット背景2" },
    ColorInfo { default_color: hexrgb(0x111111), default_light_color: hexrgb(0xDDDDDD), text: "ProgramGuideDateButtonHotBorder", name: "EPG番組表 日付ボタンホット外枠" },
    ColorInfo { default_color: hexrgb(0xFFFFE0), default_light_color: CLR_INVALID, text: "EPGContentNews", name: "EPG番組表 ニュース番組" },
    ColorInfo { default_color: hexrgb(0xE0E0FF), default_light_color: CLR_INVALID, text: "EPGContentSports", name: "EPG番組表 スポーツ番組" },
    ColorInfo { default_color: hexrgb(0xFFE0F0), default_light_color: CLR_INVALID, text: "EPGContentInformation", name: "EPG番組表 情報番組" },
    ColorInfo { default_color: hexrgb(0xFFE0E0), default_light_color: CLR_INVALID, text: "EPGContentDrama", name: "EPG番組表 ドラマ" },
    ColorInfo { default_color: hexrgb(0xE0FFE0), default_light_color: CLR_INVALID, text: "EPGContentMusic", name: "EPG番組表 音楽番組" },
    ColorInfo { default_color: hexrgb(0xE0FFFF), default_light_color: CLR_INVALID, text: "EPGContentVariety", name: "EPG番組表 バラエティ番組" },
    ColorInfo { default_color: hexrgb(0xFFF0E0), default_light_color: CLR_INVALID, text: "EPGContentMovie", name: "EPG番組表 映画" },
    ColorInfo { default_color: hexrgb(0xFFE0FF), default_light_color: CLR_INVALID, text: "EPGContentAnime", name: "EPG番組表 アニメ/特撮" },
    ColorInfo { default_color: hexrgb(0xFFFFE0), default_light_color: CLR_INVALID, text: "EPGContentDocumentary", name: "EPG番組表 ドキュメンタリー/教養番組" },
    ColorInfo { default_color: hexrgb(0xFFF0E0), default_light_color: CLR_INVALID, text: "EPGContentTheater", name: "EPG番組表 劇場/公演" },
    ColorInfo { default_color: hexrgb(0xE0F0FF), default_light_color: CLR_INVALID, text: "EPGContentEducation", name: "EPG番組表 趣味/教育番組" },
    ColorInfo { default_color: hexrgb(0xE0F0FF), default_light_color: CLR_INVALID, text: "EPGContentWelfare", name: "EPG番組表 福祉番組" },
    ColorInfo { default_color: hexrgb(0xF0F0F0), default_light_color: CLR_INVALID, text: "EPGContentOther", name: "EPG番組表 その他の番組" },
];

pub(crate) static GRADIENT_INFO_LIST: [GradientInfo; 56] = [
    GradientInfo { text: "StatusBack", direction: GradientDirection::Vert, enable_direction: false, color1: COLOR_STATUSBACK1, color2: COLOR_STATUSBACK2 },
    GradientInfo { text: "StatusBottomItemBack", direction: GradientDirection::Vert, enable_direction: false, color1: COLOR_STATUSBOTTOMITEMBACK1, color2: COLOR_STATUSBOTTOMITEMBACK2 },
    GradientInfo { text: "StatusHighlightBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_STATUSHIGHLIGHTBACK1, color2: COLOR_STATUSHIGHLIGHTBACK2 },
    GradientInfo { text: "StatusEventProgressBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_STATUSEVENTPROGRESSBACK1, color2: COLOR_STATUSEVENTPROGRESSBACK2 },
    GradientInfo { text: "StatusEventProgressElapsed", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_STATUSEVENTPROGRESSELAPSED1, color2: COLOR_STATUSEVENTPROGRESSELAPSED2 },
    GradientInfo { text: "PanelTabBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PANELTABBACK1, color2: COLOR_PANELTABBACK2 },
    GradientInfo { text: "PanelCurTabBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PANELCURTABBACK1, color2: COLOR_PANELCURTABBACK2 },
    GradientInfo { text: "PanelTabMargin", direction: GradientDirection::Vert, enable_direction: false, color1: COLOR_PANELTABMARGIN1, color2: COLOR_PANELTABMARGIN2 },
    GradientInfo { text: "PanelTitleBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PANELTITLEBACK1, color2: COLOR_PANELTITLEBACK2 },
    GradientInfo { text: "InformationPanelButtonBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_INFORMATIONPANEL_BUTTONBACK1, color2: COLOR_INFORMATIONPANEL_BUTTONBACK2 },
    GradientInfo { text: "InformationPanelHotButtonBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_INFORMATIONPANEL_HOTBUTTONBACK1, color2: COLOR_INFORMATIONPANEL_HOTBUTTONBACK2 },
    GradientInfo { text: "ProgramListChannelBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CHANNELBACK1, color2: COLOR_PROGRAMLISTPANEL_CHANNELBACK2 },
    GradientInfo { text: "ProgramListCurChannelBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CURCHANNELBACK1, color2: COLOR_PROGRAMLISTPANEL_CURCHANNELBACK2 },
    GradientInfo { text: "ProgramListChannelButtonBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONBACK1, color2: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONBACK2 },
    GradientInfo { text: "ProgramListChannelButtonHotBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONHOTBACK1, color2: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONHOTBACK2 },
    GradientInfo { text: "ProgramListBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_EVENTBACK1, color2: COLOR_PROGRAMLISTPANEL_EVENTBACK2 },
    GradientInfo { text: "ProgramListCurBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CUREVENTBACK1, color2: COLOR_PROGRAMLISTPANEL_CUREVENTBACK2 },
    GradientInfo { text: "ProgramListTitleBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_TITLEBACK1, color2: COLOR_PROGRAMLISTPANEL_TITLEBACK2 },
    GradientInfo { text: "ProgramListCurTitleBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMLISTPANEL_CURTITLEBACK1, color2: COLOR_PROGRAMLISTPANEL_CURTITLEBACK2 },
    GradientInfo { text: "ChannelPanelChannelNameBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_CHANNELNAMEBACK1, color2: COLOR_CHANNELPANEL_CHANNELNAMEBACK2 },
    GradientInfo { text: "ChannelPanelCurChannelNameBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_CURCHANNELNAMEBACK1, color2: COLOR_CHANNELPANEL_CURCHANNELNAMEBACK2 },
    GradientInfo { text: "ChannelPanelEventNameBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_EVENTNAME1BACK1, color2: COLOR_CHANNELPANEL_EVENTNAME1BACK2 },
    GradientInfo { text: "ChannelPanelEventName2Back", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_EVENTNAME2BACK1, color2: COLOR_CHANNELPANEL_EVENTNAME2BACK2 },
    GradientInfo { text: "ChannelPanelCurEventNameBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_CUREVENTNAME1BACK1, color2: COLOR_CHANNELPANEL_CUREVENTNAME1BACK2 },
    GradientInfo { text: "ChannelPanelCurEventName2Back", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_CUREVENTNAME2BACK1, color2: COLOR_CHANNELPANEL_CUREVENTNAME2BACK2 },
    GradientInfo { text: "ChannelPanelFeaturedMark", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_FEATUREDMARK1, color2: COLOR_CHANNELPANEL_FEATUREDMARK2 },
    GradientInfo { text: "ChannelPanelProgress", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_PROGRESS1, color2: COLOR_CHANNELPANEL_PROGRESS2 },
    GradientInfo { text: "ChannelPanelCurProgress", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CHANNELPANEL_CURPROGRESS1, color2: COLOR_CHANNELPANEL_CURPROGRESS2 },
    GradientInfo { text: "ControlPanelBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CONTROLPANELBACK1, color2: COLOR_CONTROLPANELBACK2 },
    GradientInfo { text: "ControlPanelHighlightBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CONTROLPANELHIGHLIGHTBACK1, color2: COLOR_CONTROLPANELHIGHLIGHTBACK2 },
    GradientInfo { text: "ControlPanelCheckedBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_CONTROLPANELCHECKEDBACK1, color2: COLOR_CONTROLPANELCHECKEDBACK2 },
    GradientInfo { text: "TitleBarBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_TITLEBARBACK1, color2: COLOR_TITLEBARBACK2 },
    GradientInfo { text: "TitleBarIconBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_TITLEBARICONBACK1, color2: COLOR_TITLEBARICONBACK2 },
    GradientInfo { text: "TitleBarHighlightBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_TITLEBARHIGHLIGHTBACK1, color2: COLOR_TITLEBARHIGHLIGHTBACK2 },
    GradientInfo { text: "SideBarBack", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_SIDEBARBACK1, color2: COLOR_SIDEBARBACK2 },
    GradientInfo { text: "SideBarHighlightBack", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_SIDEBARHIGHLIGHTBACK1, color2: COLOR_SIDEBARHIGHLIGHTBACK2 },
    GradientInfo { text: "SideBarCheckBack", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_SIDEBARCHECKBACK1, color2: COLOR_SIDEBARCHECKBACK2 },
    GradientInfo { text: "NotificationBarBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_NOTIFICATIONBARBACK1, color2: COLOR_NOTIFICATIONBARBACK2 },
    GradientInfo { text: "ProgramGuideFeaturedMark", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_FEATUREDMARK1, color2: COLOR_PROGRAMGUIDE_FEATUREDMARK2 },
    GradientInfo { text: "ProgramGuideChannelBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMGUIDE_CHANNELBACK1, color2: COLOR_PROGRAMGUIDE_CHANNELBACK2 },
    GradientInfo { text: "ProgramGuideCurChannelBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMGUIDE_CURCHANNELBACK1, color2: COLOR_PROGRAMGUIDE_CURCHANNELBACK2 },
    GradientInfo { text: "ProgramGuideTimeBack", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK1, color2: COLOR_PROGRAMGUIDE_TIMEBACK2 },
    GradientInfo { text: "ProgramGuideTime0To2Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_0TO2_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_0TO2_2 },
    GradientInfo { text: "ProgramGuideTime3To5Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_3TO5_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_3TO5_2 },
    GradientInfo { text: "ProgramGuideTime6To8Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_6TO8_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_6TO8_2 },
    GradientInfo { text: "ProgramGuideTime9To11Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_9TO11_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_9TO11_2 },
    GradientInfo { text: "ProgramGuideTime12To14Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_12TO14_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_12TO14_2 },
    GradientInfo { text: "ProgramGuideTime15To17Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_15TO17_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_15TO17_2 },
    GradientInfo { text: "ProgramGuideTime18To20Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_18TO20_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_18TO20_2 },
    GradientInfo { text: "ProgramGuideTime21To23Back", direction: GradientDirection::Horz, enable_direction: true, color1: COLOR_PROGRAMGUIDE_TIMEBACK_21TO23_1, color2: COLOR_PROGRAMGUIDE_TIMEBACK_21TO23_2 },
    GradientInfo { text: "ProgramGuideDateButtonBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMGUIDE_DATEBUTTON_BACK1, color2: COLOR_PROGRAMGUIDE_DATEBUTTON_BACK2 },
    GradientInfo { text: "ProgramGuideDateButtonCurBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMGUIDE_DATEBUTTON_CURBACK1, color2: COLOR_PROGRAMGUIDE_DATEBUTTON_CURBACK2 },
    GradientInfo { text: "ProgramGuideDateButtonHotBack", direction: GradientDirection::Vert, enable_direction: true, color1: COLOR_PROGRAMGUIDE_DATEBUTTON_HOTBACK1, color2: COLOR_PROGRAMGUIDE_DATEBUTTON_HOTBACK2 },
    GradientInfo { text: "ProgramGuideFavoriteButtonBack", direction: GradientDirection::Vert, enable_direction: true, color1: -1, color2: -1 },
    GradientInfo { text: "ProgramGuideFavoriteButtonCurBack", direction: GradientDirection::Vert, enable_direction: true, color1: -1, color2: -1 },
    GradientInfo { text: "ProgramGuideFavoriteButtonHotBack", direction: GradientDirection::Vert, enable_direction: true, color1: -1, color2: -1 },
];

pub(crate) static BORDER_INFO_LIST: [BorderInfo; 55] = [
    BorderInfo { text: "ScreenBorder", default_type: BorderType::None, color: COLOR_SCREENBORDER },
    BorderInfo { text: "WindowFrameBorder", default_type: BorderType::None, color: COLOR_WINDOWFRAMEBORDER },
    BorderInfo { text: "WindowActiveFrameBorder", default_type: BorderType::None, color: COLOR_WINDOWACTIVEFRAMEBORDER },
    BorderInfo { text: "StatusBorder", default_type: BorderType::Raised, color: COLOR_STATUSBORDER },
    BorderInfo { text: "StatusItemBorder", default_type: BorderType::None, color: COLOR_STATUSITEMBORDER },
    BorderInfo { text: "StatusBottomItemBorder", default_type: BorderType::None, color: COLOR_STATUSBOTTOMITEMBORDER },
    BorderInfo { text: "StatusHighlightBorder", default_type: BorderType::None, color: COLOR_STATUSHIGHLIGHTBORDER },
    BorderInfo { text: "StatusEventProgressBorder", default_type: BorderType::None, color: COLOR_STATUSEVENTPROGRESSBORDER },
    BorderInfo { text: "StatusEventProgressElapsedBorder", default_type: BorderType::None, color: COLOR_STATUSEVENTPROGRESSELAPSEDBORDER },
    BorderInfo { text: "TitleBarBorder", default_type: BorderType::Raised, color: COLOR_TITLEBARBORDER },
    BorderInfo { text: "TitleBarCaptionBorder", default_type: BorderType::None, color: COLOR_TITLEBARTEXTBORDER },
    BorderInfo { text: "TitleBarIconBorder", default_type: BorderType::None, color: COLOR_TITLEBARICONBORDER },
    BorderInfo { text: "TitleBarHighlightBorder", default_type: BorderType::None, color: COLOR_TITLEBARHIGHLIGHTBORDER },
    BorderInfo { text: "SideBarBorder", default_type: BorderType::Raised, color: COLOR_SIDEBARBORDER },
    BorderInfo { text: "SideBarItemBorder", default_type: BorderType::None, color: COLOR_SIDEBARITEMBORDER },
    BorderInfo { text: "SideBarHighlightBorder", default_type: BorderType::None, color: COLOR_SIDEBARHIGHLIGHTBORDER },
    BorderInfo { text: "SideBarCheckBorder", default_type: BorderType::Sunken, color: COLOR_SIDEBARCHECKBORDER },
    BorderInfo { text: "ProgramGuideStatusBorder", default_type: BorderType::Sunken, color: COLOR_STATUSBORDER },
    BorderInfo { text: "PanelTabBorder", default_type: BorderType::Solid, color: COLOR_PANELTABBORDER },
    BorderInfo { text: "PanelCurTabBorder", default_type: BorderType::Solid, color: COLOR_PANELCURTABBORDER },
    BorderInfo { text: "PanelTabMarginBorder", default_type: BorderType::None, color: COLOR_PANELTABMARGINBORDER },
    BorderInfo { text: "PanelTitleBorder", default_type: BorderType::Raised, color: COLOR_PANELTITLEBORDER },
    BorderInfo { text: "InformationPanelEventInfoBorder", default_type: BorderType::None, color: COLOR_INFORMATIONPANEL_EVENTINFOBORDER },
    BorderInfo { text: "InformationPanelButtonBorder", default_type: BorderType::None, color: COLOR_INFORMATIONPANEL_BUTTONBORDER },
    BorderInfo { text: "InformationPanelHotButtonBorder", default_type: BorderType::None, color: COLOR_INFORMATIONPANEL_HOTBUTTONBORDER },
    BorderInfo { text: "ProgramListPanelChannelBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CHANNELBORDER },
    BorderInfo { text: "ProgramListPanelCurChannelBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CURCHANNELBORDER },
    BorderInfo { text: "ProgramListPanelChannelButtonBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONBORDER },
    BorderInfo { text: "ProgramListPanelChannelButtonHotBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CHANNELBUTTONHOTBORDER },
    BorderInfo { text: "ProgramListPanelEventBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_EVENTBORDER },
    BorderInfo { text: "ProgramListPanelCurEventBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CUREVENTBORDER },
    BorderInfo { text: "ProgramListPanelTitleBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_TITLEBORDER },
    BorderInfo { text: "ProgramListPanelCurTitleBorder", default_type: BorderType::None, color: COLOR_PROGRAMLISTPANEL_CURTITLEBORDER },
    BorderInfo { text: "ChannelPanelChannelNameBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_CHANNELNAMEBORDER },
    BorderInfo { text: "ChannelPanelCurChannelNameBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_CURCHANNELNAMEBORDER },
    BorderInfo { text: "ChannelPanelEventNameBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_EVENTNAME1BORDER },
    BorderInfo { text: "ChannelPanelEventName2Border", default_type: BorderType::None, color: COLOR_CHANNELPANEL_EVENTNAME2BORDER },
    BorderInfo { text: "ChannelPanelCurEventNameBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_CUREVENTNAME1BORDER },
    BorderInfo { text: "ChannelPanelCurEventName2Border", default_type: BorderType::None, color: COLOR_CHANNELPANEL_CUREVENTNAME2BORDER },
    BorderInfo { text: "ChannelPanelFeaturedMarkBorder", default_type: BorderType::Solid, color: COLOR_CHANNELPANEL_FEATUREDMARKBORDER },
    BorderInfo { text: "ChannelPanelProgressBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_PROGRESSBORDER },
    BorderInfo { text: "ChannelPanelCurProgressBorder", default_type: BorderType::None, color: COLOR_CHANNELPANEL_CURPROGRESSBORDER },
    BorderInfo { text: "ControlPanelItemBorder", default_type: BorderType::None, color: COLOR_CONTROLPANELITEMBORDER },
    BorderInfo { text: "ControlPanelHighlightBorder", default_type: BorderType::None, color: COLOR_CONTROLPANELHIGHLIGHTBORDER },
    BorderInfo { text: "ControlPanelCheckedBorder", default_type: BorderType::None, color: COLOR_CONTROLPANELCHECKEDBORDER },
    BorderInfo { text: "ProgramGuideFeaturedMarkBorder", default_type: BorderType::Solid, color: COLOR_PROGRAMGUIDE_FEATUREDMARKBORDER },
    BorderInfo { text: "ProgramGuideDateButtonBorder", default_type: BorderType::Raised, color: COLOR_PROGRAMGUIDE_DATEBUTTON_BORDER },
    BorderInfo { text: "ProgramGuideDateButtonCurBorder", default_type: BorderType::Sunken, color: COLOR_PROGRAMGUIDE_DATEBUTTON_CURBORDER },
    BorderInfo { text: "ProgramGuideDateButtonHotBorder", default_type: BorderType::Raised, color: COLOR_PROGRAMGUIDE_DATEBUTTON_HOTBORDER },
    BorderInfo { text: "ProgramGuideTimeButtonBorder", default_type: BorderType::Raised, color: -1 },
    BorderInfo { text: "ProgramGuideTimeButtonCurBorder", default_type: BorderType::Sunken, color: -1 },
    BorderInfo { text: "ProgramGuideTimeButtonHotBorder", default_type: BorderType::Raised, color: -1 },
    BorderInfo { text: "ProgramGuideFavoriteButtonBorder", default_type: BorderType::Raised, color: -1 },
    BorderInfo { text: "ProgramGuideFavoriteButtonCurBorder", default_type: BorderType::Sunken, color: -1 },
    BorderInfo { text: "ProgramGuideFavoriteButtonHotBorder", default_type: BorderType::Raised, color: -1 },
];

pub(crate) static CUSTOM_DEFAULT_BORDER_LIST: [BorderType; 55] = [
    BorderType::None,
    BorderType::None,
    BorderType::None,
    BorderType::Raised,
    BorderType::None,
    BorderType::None,
    BorderType::Sunken,
    BorderType::None,
    BorderType::None,
    BorderType::Raised,
    BorderType::None,
    BorderType::None,
    BorderType::Sunken,
    BorderType::Raised,
    BorderType::None,
    BorderType::Sunken,
    BorderType::Sunken,
    BorderType::Sunken,
    BorderType::None,
    BorderType::Solid,
    BorderType::None,
    BorderType::Raised,
    BorderType::None,
    BorderType::None,
    BorderType::Sunken,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::None,
    BorderType::Sunken,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::Solid,
    BorderType::None,
    BorderType::None,
    BorderType::None,
    BorderType::Sunken,
    BorderType::Sunken,
    BorderType::Solid,
    BorderType::Raised,
    BorderType::Sunken,
    BorderType::Raised,
    BorderType::Raised,
    BorderType::Sunken,
    BorderType::Raised,
    BorderType::Raised,
    BorderType::Sunken,
    BorderType::Raised,
];

